# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: battleship.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62\x61ttleship.proto\x12\x0b\x62\x61ttleships\".\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08greeting\x18\x02 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"K\n\x0c\x44\x65layedReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12*\n\x07request\x18\x02 \x03(\x0b\x32\x19.battleships.HelloRequest2\xaf\x02\n\x07Greeter\x12>\n\x08SayHello\x12\x19.battleships.HelloRequest\x1a\x17.battleships.HelloReply\x12G\n\x0fParrotSaysHello\x12\x19.battleships.HelloRequest\x1a\x17.battleships.HelloReply0\x01\x12O\n\x15\x43hattyClientSaysHello\x12\x19.battleships.HelloRequest\x1a\x19.battleships.DelayedReply(\x01\x12J\n\x10InteractingHello\x12\x19.battleships.HelloRequest\x1a\x17.battleships.HelloReply(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'battleship_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=33
  _HELLOREQUEST._serialized_end=79
  _HELLOREPLY._serialized_start=81
  _HELLOREPLY._serialized_end=110
  _DELAYEDREPLY._serialized_start=112
  _DELAYEDREPLY._serialized_end=187
  _GREETER._serialized_start=190
  _GREETER._serialized_end=493
# @@protoc_insertion_point(module_scope)
